# Generated by Django 5.0.1 on 2024-02-02 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quotes',
            old_name='name',
            new_name='quote',
        ),
    ]
