# Generated by Django 5.0.1 on 2024-02-02 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0002_rename_name_quotes_quote'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quotes',
            old_name='author',
            new_name='author_id',
        ),
        migrations.AlterField(
            model_name='author',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='quotes',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
