# Generated by Django 5.0.1 on 2024-02-02 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0003_rename_author_quotes_author_id_alter_author_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotes',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
